# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYG0Dq3HjpRRo0Io6HamD3qqdvDUc20M
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ---------------------------
# PAGE CONFIG
# ---------------------------
st.set_page_config(
    page_title="Anomaly Detection System",
    page_icon="📊",
    layout="wide"
)

# ---------------------------
# CUSTOM LIGHT THEME CSS
# ---------------------------
st.markdown("""
    <style>
    .main {
        background: linear-gradient(to right, #e3f2fd, #fce4ec);
    }

    .stButton>button {
        background-color: #4CAF50;
        color: white;
        font-size: 16px;
        border-radius: 8px;
        padding: 0.5em 1em;
        border: none;
    }

    .stButton>button:hover {
        background-color: #45a049;
        color: white;
    }

    .result-box {
        padding: 20px;
        border-radius: 10px;
        background-color: #ffffff;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        margin-top: 20px;
    }

    .low {color: #2e7d32; font-weight: bold;}
    .medium {color: #f9a825; font-weight: bold;}
    .high {color: #c62828; font-weight: bold;}

    </style>
""", unsafe_allow_html=True)

# ---------------------------
# LOAD MODEL
# ---------------------------
model = joblib.load("final_xgb_model.pkl")

# ---------------------------
# HEADER
# ---------------------------
st.title("📊 Smart Anomaly Detection System")
st.markdown("### XGBoost-Based Quality Risk Prediction")

st.write("Enter process parameters to predict anomaly probability.")

# ---------------------------
# INPUT SECTION
# ---------------------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("⚙ Process Parameters")
    h_exit_ref = st.number_input("Exit Reference Thickness", value=2.0)
    velocity_mdr = st.number_input("MDR Velocity", value=0.8)
    tension_en = st.number_input("Entry Tension", value=500.0)

with col2:
    st.subheader("📈 Velocity Metrics")
    velocity_en = st.number_input("Entry Velocity", value=100.0)
    velocity_ex = st.number_input("Exit Velocity", value=100.0)

# ---------------------------
# PREDICTION
# ---------------------------
if st.button("🔍 Predict Risk"):

    input_data = pd.DataFrame({
        "h_exit_ref": [h_exit_ref],
        "velocity_mdr": [velocity_mdr],
        "tension_en": [tension_en],
        "velocity_en": [velocity_en],
        "velocity_ex": [velocity_ex],
    })

    probability = model.predict_proba(input_data)[0][1]
    threshold = 0.70
    prediction = 1 if probability > threshold else 0

    # Risk classification
    if probability < 0.3:
        risk = "Low Risk"
        risk_class = "low"
        emoji = "🟢"
    elif probability < 0.7:
        risk = "Medium Risk"
        risk_class = "medium"
        emoji = "🟡"
    else:
        risk = "High Risk"
        risk_class = "high"
        emoji = "🔴"

    st.markdown(f"""
        <div class="result-box">
            <h3>Prediction Results</h3>
            <p><b>Anomaly Probability:</b> {probability:.3f}</p>
            <p class="{risk_class}">{emoji} {risk}</p>
            <p><b>Final Decision (Threshold 0.70):</b> {"Anomaly Detected" if prediction==1 else "Normal Operation"}</p>
        </div>
    """, unsafe_allow_html=True)